// Copyright 2025 eraflo
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Open component registration system for scene serialization.
//!
//! Components register how they are written to and read from a save at link
//! time via `inventory`, and a scene is captured and applied by iterating
//! these registrations — no per-type code in the scene layer.

use super::record::{Record, RecordError, ReferenceReader, ReferenceWriter, ReportEntry};
use crate::ecs::AnyVec;
use crate::ecs::{ComponentProvenance, World};
use khora_core::ecs::entity::EntityId;
use std::any::TypeId;

/// Writes row `row` of a page column positionally into the buffer, entity
/// references through the writer — see
/// [`ComponentRegistration::column_to_snapshot`].
pub type ColumnToSnapshotFn =
    fn(&dyn AnyVec, usize, &mut Vec<u8>, &mut dyn ReferenceWriter) -> Result<(), RecordError>;

/// Registration entry for a serializable component type.
///
/// Each component that derives `Component` submits an entry via
/// `inventory::submit!` (generated by the derive macro). Saving, loading and
/// the inspector use these registrations to handle every component type.
///
/// `column_to_record` / `stage` are how a save writes and reads the component, by
/// name; `to_json` / `from_json` are the inspector's editable view. Both go
/// through the same auto-generated `Serializable<Type>` mirror, so a field
/// tagged `#[component(skip)]` is left out of both.
pub struct ComponentRegistration {
    /// The `TypeId` of the component type.
    pub type_id: TypeId,

    /// What this component looks like from outside Rust — see
    /// [`ComponentShape`](crate::scene::ComponentShape). Consumed by the Ergon
    /// mirrors, the projection, and an editor rendering a component whose crate
    /// it does not link.
    pub shape: crate::scene::ComponentShape,

    /// A human-readable name for the component (e.g., "Camera", "Light").
    pub type_name: &'static str,

    /// Who writes this component — see [`ComponentProvenance`].
    ///
    /// Lets any consumer ask "is this the author's data, or the engine's?"
    /// instead of keeping its own hand-maintained list of type names. The
    /// editor's "Add Component" menu and `duplicate_entity` both read it, so
    /// components declared outside this crate are handled correctly too.
    pub provenance: ComponentProvenance,

    /// Other names saves may hold this component under — the names it had
    /// before it was renamed. Read as this component; written under its
    /// current name.
    pub formerly: &'static [&'static str],

    /// Whether a game save keeps this component so play can resume where it
    /// stopped, although a scene never holds it — declared with
    /// `#[component(resumable)]` on state the engine writes while running.
    pub resumable: bool,

    /// Writes row `row` of a page column of this component as a record, its
    /// entity references through `references`.
    ///
    /// A column, not an entity: a scene is captured page by page, the unit
    /// CRPECS stores and serializes data in. The column may be laid out any
    /// way the component chose (array of structs, field-split SoA); the value
    /// is read whole and written by name, so the layout never reaches a file.
    pub column_to_record:
        fn(&dyn AnyVec, usize, &mut dyn ReferenceWriter) -> Result<Record, RecordError>,

    /// Reads the component back from a record, its references through
    /// `references`, without touching any world: what the load would add,
    /// and what reading it adapted.
    pub stage: fn(&Record, &mut dyn ReferenceReader) -> Result<Staged, RecordError>,

    /// The fingerprint of the schema this component is written in by a
    /// snapshot — the canonical trace of its mirror's serde format, hashed.
    /// A snapshot is read only by the schema that wrote it.
    pub schema: fn() -> u64,

    /// Whether the schema was traced in full. A component whose schema was
    /// not cannot be told apart from a later version of itself, so it is
    /// never written to, nor read from, a snapshot.
    pub schema_complete: fn() -> bool,

    /// Writes row `row` of a page column of this component positionally —
    /// no names, its references through `references` — appending to `out`.
    pub column_to_snapshot: ColumnToSnapshotFn,

    /// Reads the component back from the bytes a snapshot holds for it, which
    /// must be consumed exactly, its references through `references`.
    pub stage_snapshot: fn(&[u8], &mut dyn ReferenceReader) -> Result<Staged, RecordError>,

    /// Creates a default instance of this component and adds it to the entity.
    /// Used by the editor's "Add Component" UI.
    pub create_default: fn(&mut World, EntityId) -> Result<(), String>,

    /// Returns a JSON view of the component on `entity`, or `None` if the
    /// entity doesn't have it. The conversion goes through the generated
    /// `Serializable<Type>` mirror, so any field tagged `#[component(skip)]`
    /// is omitted, as it is from a saved record.
    pub to_json: fn(&World, EntityId) -> Option<serde_json::Value>,

    /// Applies a JSON value back to the component on `entity`. Used by the
    /// editor inspector to commit field edits without per-type code.
    /// Implementations should be tolerant of partial updates by deserialising
    /// against the full mirror struct first.
    pub from_json: fn(&mut World, EntityId, &serde_json::Value) -> Result<(), String>,

    /// Removes this component alone from `entity`, leaving every other
    /// component in place. Used by the editor inspector's per-card delete
    /// button to drop a component by `type_name` lookup.
    pub remove: fn(&mut World, EntityId) -> Result<(), String>,
}

inventory::collect!(ComponentRegistration);

/// A component read from a save, not yet in any world.
///
/// A load reads every component before it adds any, so that one that cannot
/// be read leaves the world as it was. This is what it holds in between.
pub struct Staged {
    /// The component, ready to add.
    pub component: Box<dyn StagedComponent>,
    /// What reading it adapted — paths only; the load names the entity.
    pub report: Vec<ReportEntry>,
}

/// A component value waiting to be added to an entity.
pub trait StagedComponent: Send {
    /// Appends the value as a new row of its page column — how a load builds
    /// a page, a row at a time, without migrating the entity.
    fn push_into(self: Box<Self>, column: &mut dyn AnyVec);

    /// Adds the component to `entity` on its own, outside a page being built.
    fn commit(self: Box<Self>, world: &mut World, entity: EntityId) -> Result<(), String>;
}

/// A typed component waiting to be added.
pub struct StagedValue<T>(pub T);

impl<T: crate::ecs::Component> StagedComponent for StagedValue<T> {
    fn push_into(self: Box<Self>, column: &mut dyn AnyVec) {
        self.0.push_into_column(column);
    }

    fn commit(self: Box<Self>, world: &mut World, entity: EntityId) -> Result<(), String> {
        world
            .add_component(entity, self.0)
            .map(|_| ())
            .map_err(|error| format!("{error:?}"))
    }
}

/// The component `reg` describes on `entity`, written as a record — the
/// column row it occupies, read through the registration. `None` when the
/// entity does not have it.
pub fn component_to_record(
    reg: &ComponentRegistration,
    world: &World,
    entity: EntityId,
    references: &mut dyn ReferenceWriter,
) -> Option<Result<Record, RecordError>> {
    let (column, row) = world.component_cell(entity, reg.type_id)?;
    Some((reg.column_to_record)(column, row, references))
}

/// Copies `reg`'s component from `entity` in `src` onto `target` in `dst`
/// through a record — what a save then a load does to one component. Entity
/// references keep the ids they had, so a component holding one compares
/// equal on both sides.
#[cfg(test)]
pub(crate) fn copy_through_record(
    reg: &ComponentRegistration,
    src: &World,
    entity: EntityId,
    dst: &mut World,
    target: EntityId,
) -> Option<Result<(), String>> {
    use super::record::EntityRef;
    use khora_core::ecs::PersistentId;

    struct Same;
    impl ReferenceWriter for Same {
        fn write_entity(&mut self, entity: EntityId) -> EntityRef {
            EntityRef::Id(PersistentId::from_bits(
                (u64::from(entity.index) << 32) | u64::from(entity.generation),
            ))
        }
    }
    impl ReferenceReader for Same {
        fn read_entity(&mut self, reference: EntityRef) -> Result<EntityId, RecordError> {
            match reference {
                EntityRef::Id(id) => Ok(EntityId {
                    index: (id.to_bits() >> 32) as u32,
                    generation: id.to_bits() as u32,
                }),
                EntityRef::Outside => Err(RecordError("an outside reference".to_owned())),
            }
        }
    }

    let record = match component_to_record(reg, src, entity, &mut Same)? {
        Ok(record) => record,
        Err(error) => return Some(Err(error.to_string())),
    };
    Some(
        (reg.stage)(&record, &mut Same)
            .map_err(|error| error.to_string())
            .and_then(|staged| staged.component.commit(dst, target)),
    )
}

impl ComponentRegistration {
    /// Whether a save holds this component: one an author or a tool wrote,
    /// not one the engine derives or writes while running.
    pub fn is_saved(&self) -> bool {
        self.provenance.is_copied_on_duplicate()
    }

    /// Whether a game save keeps this component although a scene does not:
    /// state the engine wrote while running and reads back to resume —
    /// declared with `#[component(resumable)]`.
    pub fn is_resumed(&self) -> bool {
        self.resumable
    }
}

/// Which components a document keeps.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum Kept {
    /// A scene: what an author or a tool wrote.
    Scene,
    /// A game save: that, and the state the engine wrote while running that
    /// play needs to resume.
    Game,
}

impl Kept {
    /// Whether this kind of document keeps `reg`'s component.
    pub(crate) fn keeps(self, reg: &ComponentRegistration) -> bool {
        match self {
            Self::Scene => reg.is_saved(),
            Self::Game => reg.is_saved() || reg.is_resumed(),
        }
    }
}

/// The registration a save names `type_name` by: its current name, or one it
/// was known by before.
pub fn registration_named(type_name: &str) -> Option<&'static ComponentRegistration> {
    inventory::iter::<ComponentRegistration>
        .into_iter()
        .find(|reg| reg.type_name == type_name)
        .or_else(|| {
            inventory::iter::<ComponentRegistration>
                .into_iter()
                .find(|reg| reg.formerly.contains(&type_name))
        })
}

/// Looks up the registration of a component by its `type_name`.
///
/// The generic script-command path resolves a component this way rather than
/// carrying a second registry of its own: `#[derive(Component)]` already emits
/// everything needed to create, patch and drop a component without per-type
/// code, and a parallel table would be one more thing to keep in step.
pub fn registration_of(type_name: &str) -> Option<&'static ComponentRegistration> {
    inventory::iter::<ComponentRegistration>
        .into_iter()
        .find(|reg| reg.type_name == type_name)
}

/// Looks up the registered provenance of a component by its `type_name`.
///
/// Returns `None` for a type that never registered — the generic
/// `HandleComponent<T>` instantiations and anything tagged
/// `#[component(no_serializable)]`, neither of which participates in
/// serialization, duplication or the "Add Component" menu.
pub fn provenance_of(type_name: &str) -> Option<ComponentProvenance> {
    inventory::iter::<ComponentRegistration>
        .into_iter()
        .find(|reg| reg.type_name == type_name)
        .map(|reg| reg.provenance)
}

#[cfg(test)]
mod provenance_tests {
    use super::*;

    /// Locks the classification of the components whose provenance is not the
    /// default. Each of these was previously encoded in a hand-maintained list
    /// somewhere else in the workspace; if one silently reverts to `Authored`
    /// it would reappear in "Add Component" and be copied on duplicate.
    #[test]
    fn engine_written_components_are_classified() {
        // Recomputed by `transform_propagation` from Transform + Parent.
        assert_eq!(
            provenance_of("GlobalTransform"),
            Some(ComponentProvenance::Derived)
        );
        // Inverse index of `Parent`, maintained by `World::set_parent`.
        // Copying it would make a duplicate claim the original's children.
        assert_eq!(
            provenance_of("Children"),
            Some(ComponentProvenance::Derived)
        );
        // Set by dragging in the scene tree; persists and must survive a
        // duplicate, but adding an empty one by hand is meaningless.
        assert_eq!(
            provenance_of("Parent"),
            Some(ComponentProvenance::ToolAuthored)
        );
        // Debug output of the physics writeback.
        assert_eq!(
            provenance_of("PhysicsDebugData"),
            Some(ComponentProvenance::Runtime)
        );
        // What the script lane observed, written back by the engine: never
        // authored, never in a scene.
        assert_eq!(
            provenance_of("ScriptState"),
            Some(ComponentProvenance::Runtime)
        );
    }

    /// **A save resumes a behavior where it was.** `ScriptState` is written
    /// while running, so a scene never holds it — but a game save does, and
    /// that is what `is_resumed` says.
    #[test]
    fn script_state_is_runtime_and_resumable() {
        let reg = registration_of("ScriptState").expect("ScriptState is registered");
        assert_eq!(reg.provenance, ComponentProvenance::Runtime);
        assert!(!reg.is_saved(), "a scene never holds observed state");
        assert!(reg.is_resumed(), "a game save keeps it to resume");
    }

    /// Only `ScriptState` is resumable for now. Marking another component is
    /// a decision about how its domain reads it back on load, not a flag to
    /// set in passing.
    #[test]
    fn no_other_component_is_resumed() {
        let resumed: Vec<&str> = inventory::iter::<ComponentRegistration>
            .into_iter()
            .filter(|reg| reg.is_resumed())
            .map(|reg| reg.type_name)
            .collect();
        assert_eq!(resumed, vec!["ScriptState"]);
    }

    /// Resumable is about what the engine wrote: no component an author or a
    /// tool writes is also resumed, so a save never holds a value twice.
    #[test]
    fn a_resumed_component_is_never_also_saved() {
        for reg in inventory::iter::<ComponentRegistration> {
            assert!(
                !(reg.is_saved() && reg.is_resumed()),
                "{} is both saved and resumed",
                reg.type_name
            );
        }
    }

    /// **A marker is a component, and a scene has to record it.**
    ///
    /// `ActiveEvents` and `AudioListener` carried
    /// `#[component(no_serializable)]`, which does not mean "runtime state" —
    /// it drops the `ComponentRegistration` outright, so no serializer ever
    /// knew the type existed. Saving a scene and loading it back removed both:
    /// the collider stopped reporting contacts, and the scene came back deaf.
    /// `provenance_of` returning `None` is the shape of that bug.
    #[test]
    fn a_marker_component_is_registered_and_authored() {
        for marker in ["ActiveEvents", "AudioListener"] {
            assert_eq!(
                provenance_of(marker),
                Some(ComponentProvenance::Authored),
                "{marker} must be recorded in a scene — somebody put it there on purpose"
            );
        }
    }

    /// The components a user actually authors keep the default, including the
    /// two whose registration is hand-written rather than derive-generated.
    #[test]
    fn authored_components_keep_the_default() {
        for name in [
            "Transform",
            "Camera",
            "Light",
            "Tag",
            "MeshRef",
            "MaterialRef",
        ] {
            assert_eq!(
                provenance_of(name),
                Some(ComponentProvenance::Authored),
                "{name} should be author-written"
            );
        }
    }

    /// The two halves of the hierarchy edge are classified differently, and
    /// the asymmetry is the point.
    ///
    /// `Parent` is written by the reparent action, so it persists and a
    /// duplicate keeps it — but nobody adds one from a menu, hence
    /// `ToolAuthored`. `Children` is merely the inverse index rebuilt from it,
    /// so it is `Derived` and must never be copied verbatim.
    #[test]
    fn parent_and_children_are_classified_asymmetrically() {
        let parent = provenance_of("Parent").expect("Parent is registered");
        let children = provenance_of("Children").expect("Children is registered");

        assert!(!parent.is_hand_authorable());
        assert!(parent.is_copied_on_duplicate());

        assert!(!children.is_hand_authorable());
        assert!(!children.is_copied_on_duplicate());
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ecs::component::Component;
    use crate::ecs::{
        AudioSource, Camera, Children, GlobalTransform, Light, Name, Parent, SemanticDomain, Tag,
        Transform,
    };
    use khora_core::math::Vec3;

    /// A test-only anchor component. A fresh round-trip target entity is
    /// spawned carrying only this, so it exists in the world without already
    /// owning any component the round-trip is about to add — every
    /// `from_json` / `stage` exercises the real "add" path.
    #[derive(Debug, Clone, Copy, PartialEq, Eq)]
    struct Anchor;
    impl Component for Anchor {}

    /// Spawns the round-trip target: a live entity carrying only [`Anchor`],
    /// in a world where `Anchor` is registered (its own page domain) so adding
    /// any real component triggers a genuine migration.
    fn spawn_anchor_target(world: &mut World) -> EntityId {
        world.register_component::<Anchor>(SemanticDomain::Ui);
        world.spawn(Anchor)
    }

    /// Spawns one entity carrying a broad, representative instance of every
    /// commonly-authored component, with non-default field values where the
    /// type allows it. The returned entity is the JSON/record round-trip
    /// fixture for [`json_roundtrip_covers_every_present_component`] and
    /// [`record_roundtrip_covers_every_present_component`].
    ///
    /// Components reached here are exercised end-to-end: the entity *has* them,
    /// so `to_json` / `column_to_record` return `Some` and the parallel
    /// `from_json` / `stage` paths are driven on a fresh entity.
    fn spawn_representative_entity(world: &mut World) -> EntityId {
        // A second entity so `Parent`/`Children` carry real ids.
        let other = world.spawn((Transform::identity(), GlobalTransform::identity()));

        let mut tags = Tag::new();
        tags.insert("enemy");
        tags.insert("boss");

        world.spawn((
            Transform::from_translation(Vec3::new(1.5, -2.0, 3.25)),
            GlobalTransform::at_position(Vec3::new(1.5, -2.0, 3.25)),
            Name::new("Fixture"),
            Camera::new_perspective(std::f32::consts::FRAC_PI_3, 1.5, 0.05, 500.0),
            Light::point(),
            AudioSource::default(),
            crate::ecs::AudioListener,
            crate::ecs::ActiveEvents,
            tags,
            Parent(other),
            Children(vec![other]),
        ))
    }

    /// The editor inspector round-trip: for every registered component the
    /// fixture entity carries, `to_json` must yield a value, and feeding that
    /// value to `from_json` on a fresh entity in a fresh world must re-create
    /// the component with the same JSON shape. This one test catches macro
    /// `to_json`/`from_json` generation bugs, registry wiring gaps, and serde
    /// breakage across the whole component set in a single pass.
    #[test]
    fn json_roundtrip_covers_every_present_component() {
        let mut src = World::new();
        let entity = spawn_representative_entity(&mut src);

        let mut covered = 0usize;
        for reg in inventory::iter::<ComponentRegistration> {
            let Some(json) = (reg.to_json)(&src, entity) else {
                // The fixture entity doesn't carry this component — nothing to
                // assert for it here.
                continue;
            };
            covered += 1;

            // Fresh world + fresh entity: `from_json` must reconstruct the
            // component from the captured JSON alone.
            let mut dst = World::new();
            let target = spawn_anchor_target(&mut dst);
            (reg.from_json)(&mut dst, target, &json).unwrap_or_else(|e| {
                panic!("from_json failed for {}: {}", reg.type_name, e);
            });

            let restored = (reg.to_json)(&dst, target).unwrap_or_else(|| {
                panic!(
                    "{} missing after from_json — component was not added",
                    reg.type_name
                )
            });
            assert_eq!(
                restored, json,
                "{} JSON did not round-trip through from_json",
                reg.type_name
            );
        }

        // Sanity: the fixture must reach a meaningful slice of the registry,
        // otherwise a silent registration regression could make this test
        // pass vacuously.
        assert!(
            covered >= 6,
            "expected the fixture to cover at least 6 components, got {covered}"
        );
    }

    /// The save round-trip: a record of each component mirrors the JSON path
    /// through the same `Serializable<Type>` mirror. For every component the
    /// fixture carries, `column_to_record` must write it and `stage` must re-add it
    /// on a fresh entity, with the JSON view matching afterwards.
    #[test]
    fn record_roundtrip_covers_every_present_component() {
        let mut src = World::new();
        let entity = spawn_representative_entity(&mut src);

        for reg in inventory::iter::<ComponentRegistration> {
            let before = (reg.to_json)(&src, entity);
            let mut dst = World::new();
            let target = spawn_anchor_target(&mut dst);
            let Some(copied) = copy_through_record(reg, &src, entity, &mut dst, target) else {
                continue;
            };
            copied.unwrap_or_else(|e| {
                panic!("the record round trip failed for {}: {}", reg.type_name, e);
            });

            let after = (reg.to_json)(&dst, target);
            assert!(
                after.is_some(),
                "{} missing after the record round trip",
                reg.type_name
            );
            assert_eq!(
                after, before,
                "{} did not round-trip through a record",
                reg.type_name
            );
        }
    }
}
