// Copyright 2025 eraflo
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Open component registration system for scene serialization.
//!
//! Components register their serialization/deserialization functions
//! at link time via `inventory`. The Definition and Recipe strategies
//! iterate these registrations to handle all component types.

use crate::ecs::World;
use khora_core::ecs::entity::EntityId;
use std::any::TypeId;

/// Registration entry for a serializable component type.
///
/// Each component that derives `Component` submits an entry via
/// `inventory::submit!` (generated by the derive macro). The serialization
/// strategies use these registrations to handle all component types automatically.
pub struct ComponentRegistration {
    /// The `TypeId` of the component type.
    pub type_id: TypeId,

    /// A human-readable name for the component (e.g., "Camera", "Light").
    pub type_name: &'static str,

    /// Serializes the component from the world into a Recipe command's
    /// component_data bytes. Returns `None` if the entity doesn't have
    /// this component.
    pub serialize_recipe: fn(&World, EntityId) -> Option<Vec<u8>>,

    /// Deserializes a Recipe command's component_data bytes and adds
    /// the component to the entity.
    pub deserialize_recipe: fn(&mut World, EntityId, &[u8]) -> Result<(), String>,

    /// Creates a default instance of this component and adds it to the entity.
    /// Used by the editor's "Add Component" UI.
    pub create_default: fn(&mut World, EntityId) -> Result<(), String>,
}

inventory::collect!(ComponentRegistration);

/// Helper function to serialize a component from a world.
///
/// Tries each registered component type to find one that matches
/// and can serialize the given entity's component.
pub fn serialize_all_components(world: &World, entity: EntityId) -> Vec<(String, Vec<u8>)> {
    let mut results = Vec::new();
    for reg in inventory::iter::<ComponentRegistration> {
        if let Some(data) = (reg.serialize_recipe)(world, entity) {
            results.push((reg.type_name.to_string(), data));
        }
    }
    results
}
