[workspace]
resolver = "2" # Recommended for modern Rust
members = [
    # Legacy crates (to be migrated)
    "khora_engine_core", # The future engine 'core'
    "sandbox-legacy",      # Legacy example/test application
    
    # New modular architecture
    "crates/khora-core",
    "crates/khora-control", 
    "crates/khora-data",
    "crates/khora-lanes",
    "crates/khora-agents",
    "crates/khora-infra",
    "crates/khora-editor",
    "crates/khora-plugins",
    "crates/khora-sdk",
    
    # Examples and tools
    "examples/sandbox",
    "xtask",
]


[profile.dev]
opt-level = 1 # Enable minimal optimization even in dev

[profile.release]
lto = true      # Link-Time Optimization for release
codegen-units = 1 # Maximize optimizations (compiles slower)