[package]
name = "khora_engine_core"
version = "0.1.0"
edition = "2024"

[dependencies]
approx = "0.5"
log = "0.4"
env_logger = "0.10"
flume = "0.11"
winit = "0.30"

raw-window-handle = "0.6" 

[features]
default = ["raw-window-handle"]
raw-window-handle = []